<?php
/**
 * @file
 * Code for the Entity Form Access.
 */

function devsigner_access_entityform_access_alter(&$access, $op, $context) {
  switch ($op) {
    case 'view':

      // If admin return with no alteration of permissions
      if (is_array($context['account']->roles) && in_array('administrator', $context['account']->roles)) {
        return true;

      // Block views for anything that's not a session
      } else if ($context['entityform']->type != 'session') {
        $access = 0;
      }
      break;
  }
}